### ISSUE TITLE
PowerJob worker reported table not found.

### ISSUE THREAD

**Issue by jjnnzb** [KFCFans/PowerJob#41]
**Describe the bug**
As recommended, I set `config.setStoreStrategy(StoreStrategy.DISK);`, the jar would run for hours safely, and then suddenly report H2 table TASK_INFO not found.

```
2020-07-29 08:30:55.268  ERROR 38782 --- [ctttp-168638049960329280-1] c.g.k.p.w.p.TaskPersistenceService       TaskPersistenceService.java:217: [TaskPersistenceService] getTaskStatusStatistics for instance(id=168638049960329280) failed.
org.h2.jdbc.JdbcSQLException: Table "TASK_INFO" not found; SQL statement:
select status, count(*) as num from task_info where sub_instance_id = 168638049960329280 and instance_id = 168638049960329280GROUP BY status [42102-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5920)
	at org.h2.command.Parser.readTableFilter(Parser.java:1430)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2138)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2287)
	at org.h2.command.Parser.parseSelectSub(Parser.java:2133)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1946)
	at org.h2.command.Parser.parseSelect(Parser.java:1919)
	at org.h2.command.Parser.parsePrepared(Parser.java:463)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:310)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at com.github.kfcfans.powerjob.worker.persistence.TaskDAOImpl.simpleQueryPlus(TaskDAOImpl.java:99)
	at com.github.kfcfans.powerjob.worker.persistence.TaskPersistenceService.lambda$getTaskStatusStatistics$10(TaskPersistenceService.java:206)
	at com.github.kfcfans.powerjob.common.utils.CommonUtils.executeWithRetry(CommonUtils.java:44)
	at com.github.kfcfans.powerjob.worker.persistence.TaskPersistenceService.execute(TaskPersistenceService.java:340)
	at com.github.kfcfans.powerjob.worker.persistence.TaskPersistenceService.getTaskStatusStatistics(TaskPersistenceService.java:205)
	at com.github.kfcfans.powerjob.worker.core.tracker.task.TaskTracker.getInstanceStatisticsHolder(TaskTracker.java:401)
	at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.innerRun(CommonTaskTracker.java:127)
	at com.github.kfcfans.powerjob.worker.core.tracker.task.CommonTaskTracker$StatusCheckRunnable.run(CommonTaskTracker.java:294)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**To Reproduce**
1. Set config.setStoreStrategy(StoreStrategy.DISK);
2. Deploy the jar, run and let go.
3. Wait for hours and see.

**Expected behavior**
Task Executing error as shown in the following screenshot.

**Environment**
 - PowerJob Version: [3.1.2]
 - Java Version: [java version "1.8.0_101" Java(TM) SE Runtime Environment (build 1.8.0_101-b13) Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)]
 - OS: [CentOS Linux release 7.2.1511 (Core) ]

**Screenshots**
![Capture20200731100755](https://user-images.githubusercontent.com/58833386/88992577-5ced0580-d316-11ea-9377-3935c7fb2057.png)

**Comment by jjnnzb** [comment]
![Capture20200731100755](https://user-images.githubusercontent.com/58833386/88992639-89a11d00-d316-11ea-943c-cf9597ec3046.png)

**Comment by KFCFans** [comment]
根据 https://stackoverflow.com/questions/5763747/h2-in-memory-database-table-not-found 描述，可能是 H2 数据库大小写的问题。
目前比较迷的地方是它不是必现的。在我的测试平台上一直没有出现问题，在你的机器上好像一直有这个问题...
我已经按照[stackoverflow](https://stackoverflow.com/questions/5763747/h2-in-memory-database-table-not-found)里面的方法做了修改，也预计在下个版本发布。
PS：你可以先试试 v3.2.2 分支上的代码，因为我本地没办法复现这个问题，所以也不知道实际解决问题没有...

**Comment by jjnnzb** [comment]
> 根据 https://stackoverflow.com/questions/5763747/h2-in-memory-database-table-not-found 描述，可能是 H2 数据库大小写的问题。
> 目前比较迷的地方是它不是必现的。在我的测试平台上一直没有出现问题，在你的机器上好像一直有这个问题...
> 我已经按照[stackoverflow](https://stackoverflow.com/questions/5763747/h2-in-memory-database-table-not-found)里面的方法做了修改，也预计在下个版本发布。
> PS：你可以先试试 v3.2.2 分支上的代码，因为我本地没办法复现这个问题，所以也不知道实际解决问题没有...

修复之后，同一台机器上的多个worker都设置了
`config.setStoreStrategy(StoreStrategy.MEMORY);`
可以一起运行吗？

**Comment by KFCFans** [comment]
可以的，之后无论选 DISK 和 MEMORY 都可以在一台机器上启动多个实例

**Comment by KFCFans** [comment]
since v3.2.2

**Comment by AZI-D** [comment]
> > 根据 https://stackoverflow.com/questions/5763747/h2-in-memory-database-table-not-found 描述，可能是 H2 数据库大小写的问题。
> > 目前比较迷的地方是它不是必现的。在我的测试平台上一直没有出现问题，在你的机器上好像一直有这个问题...
> > 我已经按照[stackoverflow](https://stackoverflow.com/questions/5763747/h2-in-memory-database-table-not-found)里面的方法做了修改，也预计在下个版本发布。
> > PS：你可以先试试 v3.2.2 分支上的代码，因为我本地没办法复现这个问题，所以也不知道实际解决问题没有...
> 
> 修复之后，同一台机器上的多个worker都设置了 `config.setStoreStrategy(StoreStrategy.MEMORY);` 可以一起运行吗？

你好，在设置config.setStoreStrategy(StoreStrategy.MEMORY)后，这个问题还出现过吗？
