### ISSUE TITLE
idea本地启动后访问localhost:7700，当前运行实例数为0，创建的job执行找不到worker

### ISSUE THREAD

**Issue by xianwdong** [KFCFans/PowerJob#44]
所有配置仅修改server中的数据库配置，访问的项目是powerjob-agent-test

**Comment by ivan132** [comment]
遇到了同样的问题
![image](https://user-images.githubusercontent.com/1582699/89396727-7be9fe00-d741-11ea-8dc2-3127e45fc3f2.png)

**Comment by KFCFans** [comment]
有启动 powerjob-worker 连接 server 吗？
server 只是一个调度器，需要 worker 来执行任务...

可以参考这个教程在本地搭建一个试用环境：https://www.yuque.com/powerjob/guidence/nyio9g

**Comment by xianwdong** [comment]
> 有启动 powerjob-worker 连接 server 吗？
> server 只是一个调度器，需要 worker 来执行任务...
> 
> 可以参考这个教程在本地搭建一个试用环境：https://www.yuque.com/powerjob/guidence/nyio9g

启动了项目的powerjob-server和powerjob-worker-samples

**Comment by KFCFans** [comment]
那你需要给我更多的信息，比如 server 端的日志 和 worker 端的日志。
描述问题尽可能携带更多可能有帮助的信息，这样才能快速解决问题～

**Comment by dudiao** [comment]
worker端上报时，出现异常，我在`WorkerHealthReporter`中添加了`try catch`后
```java
@Slf4j
@AllArgsConstructor
public class WorkerHealthReporter implements Runnable {

    @Override
    public void run() {

        // 没有可用Server，无法上报
        try {
            String currentServer = OhMyWorker.getCurrentServer();
            log.info("current server is: {}", currentServer);
            if (StringUtils.isEmpty(currentServer)) {
                return;
            }

            SystemMetrics systemMetrics = SystemInfoUtils.getSystemMetrics();
            WorkerHeartbeat heartbeat = new WorkerHeartbeat();

            heartbeat.setSystemMetrics(systemMetrics);
            heartbeat.setWorkerAddress(OhMyWorker.getWorkerAddress());
            heartbeat.setAppName(OhMyWorker.getConfig().getAppName());
            heartbeat.setAppId(OhMyWorker.getAppId());
            heartbeat.setHeartbeatTime(System.currentTimeMillis());
            heartbeat.setVersion(OmsWorkerVersion.getVersion());

            // 获取当前加载的容器列表
            heartbeat.setContainerInfos(OmsContainerFactory.getDeployedContainerInfos());

            // 发送请求
            String serverPath = AkkaUtils.getAkkaServerPath(RemoteConstant.SERVER_ACTOR_NAME);
            if (StringUtils.isEmpty(serverPath)) {
                return;
            }
            ActorSelection actorSelection = OhMyWorker.actorSystem.actorSelection(serverPath);
            actorSelection.tell(heartbeat, null);
        } catch (Exception e) {
            log.warn("WorkerHealthReporter exception", e);
        }
    }
}
```
控制台打印：
```java
2020-08-06 09:54:53 WARN  - WorkerHealthReporter exception
java.lang.NumberFormatException: For input string: "1,049.6284"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.github.kfcfans.powerjob.worker.common.utils.SystemInfoUtils.miniDouble(SystemInfoUtils.java:79)
	at com.github.kfcfans.powerjob.worker.common.utils.SystemInfoUtils.bytes2GB(SystemInfoUtils.java:75)
	at com.github.kfcfans.powerjob.worker.common.utils.SystemInfoUtils.fillDiskInfo(SystemInfoUtils.java:70)
	at com.github.kfcfans.powerjob.worker.common.utils.SystemInfoUtils.getSystemMetrics(SystemInfoUtils.java:37)
	at com.github.kfcfans.powerjob.worker.background.WorkerHealthReporter.run(WorkerHealthReporter.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
**解决：**

1. NumberFormat不按照千分位输出
```java
public class SystemInfoUtils {

    private static final NumberFormat NF = NumberFormat.getNumberInstance();
    static {
        NF.setMaximumFractionDigits(4);
        NF.setMinimumFractionDigits(4);
        NF.setRoundingMode(RoundingMode.HALF_UP);
        // 不按照千分位输出
        NF.setGroupingUsed(false);
    }

}
```

2. 各种线程需要使用try catch，防止异常被吞掉

**Comment by ivan132** [comment]
> 那你需要给我更多的信息，比如 server 端的日志 和 worker 端的日志。
> 描述问题尽可能携带更多可能有帮助的信息，这样才能快速解决问题～

[sampleApplicationlog.txt](https://github.com/KFCFans/PowerJob/files/5032124/sampleApplicationlog.txt)
[serverlog.txt](https://github.com/KFCFans/PowerJob/files/5032125/serverlog.txt)

**Comment by KFCFans** [comment]
@ivan132 抱歉，代码 bug。
master 分支已修复，正式的 jar 依赖预计明天可用。

**Comment by ivan132** [comment]
> @ivan132 抱歉，代码 bug。
> master 分支已修复，正式的 jar 依赖预计明天可用。

太客气了，正在学习中，非常感谢！

**Comment by KFCFans** [comment]
@dudiao 你居然能复现...厉害......
这个触发条件是 1TB 以上的磁盘或内存容量吧......
不容易......

以后陌生的 API 不敢乱用了......居然会在格式化的时候加个逗号，顶不住......

**Comment by dudiao** [comment]
公司电脑，内存小，就磁盘大点，前两天就遇到了，UI一直不显示客户端，一点一点debug的😂

@KFCFans 话说，线程里是不是要try catch一下，这个bug关键问题在于异常被吞了。

**Comment by KFCFans** [comment]
👍👍👍

发现了咋不反馈下......你觉得是小 bug 吗……
这个 bug 还是大的


读钓 <notifications@github.com>于2020年8月6日 周四下午1:45写道：

**Comment by dudiao** [comment]
前天晚上发现的，debug到了WorkerHealthReporter那块，然后一忙起来就忘了，今天上了下github才发现。🤣

**Comment by KFCFans** [comment]
> 前天晚上发现的，debug到了WorkerHealthReporter那块，然后一忙起来就忘了，今天上了下github才发现。🤣

哈哈哈，总之这次多亏了你～这原因不好找啊，啥堆栈都没有。
