### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by china0402** [KFCFans/PowerJob#46]
**Describe the bug**
这个我配置开源项目，第一次启动就报错的，桑心

10:07:03.799 [main] INFO com.github.kfcfans.powerjob.server.akka.OhMyServer - [OhMyServer] OhMyServer's akka system start to bootstrap...
10:07:03.805 [main] INFO com.github.kfcfans.powerjob.server.akka.OhMyServer - [OhMyWorker] akka-remote server address: 10.13.48.87:10086
10:07:04.399 [oms-server-akka.actor.default-dispatcher-5] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
10:07:04.521 [oms-server-akka.actor.default-dispatcher-5] WARN akka.remote.RemoteActorRefProvider - Using the 'remote' ActorRefProvider directly, which is a low-level layer. For most use cases, the 'cluster' abstraction on top of remoting is more suitable instead.
10:07:04.521 [oms-server-akka.actor.default-dispatcher-5] WARN akka.remote.RemoteActorRefProvider - Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
Exception in thread "main" java.util.NoSuchElementException
	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:608)
	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:606)
	at scala.collection.immutable.HashMap.apply(HashMap.scala:131)
	at akka.serialization.Serialization.$anonfun$bindings$3(Serialization.scala:438)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
	at scala.collection.immutable.HashMapBuilder.addAll(HashMap.scala:2338)
	at scala.collection.immutable.HashMap$.from(HashMap.scala:2162)
	at scala.collection.immutable.HashMap$.from(HashMap.scala:2138)
	at scala.collection.MapOps$WithFilter.map(Map.scala:353)
	at akka.serialization.Serialization.<init>(Serialization.scala:436)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:18)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:14)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1155)
	at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1196)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1191)
	at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1209)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1036)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1023)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1023)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1046)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:283)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:327)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:301)
	at akka.actor.ActorSystem$.create(ActorSystem.scala:224)
	at akka.actor.ActorSystem.create(ActorSystem.scala)
	at com.github.kfcfans.powerjob.server.akka.OhMyServer.init(OhMyServer.java:60)
	at com.github.kfcfans.powerjob.server.OhMyApplication.main(OhMyApplication.java:33)

**Environment**
 - PowerJob Version: master
 - Java Version: JDK 1.8.0_191

**Comment by KFCFans** [comment]
看堆栈似乎是 Akka 内部错误...要不rebuild后重试下试试？
第一次见这种神奇的错误......

青岑 <notifications@github.com>于2020年8月7日 周五上午10:11写道：
