### ISSUE TITLE
使用postgresql数据库时 报错

### ISSUE THREAD

**Issue by jamespatriot** [KFCFans/PowerJob#60]
org.springframework.orm.jpa.JpaSystemException: Unable to access lob stream; nested exception is org.hibernate.HibernateException: Unable to access lob stream
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:353)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy139.findByInstanceId(Unknown Source)
        at com.github.kfcfans.powerjob.server.service.instance.InstanceService.fetchInstanceInfo(InstanceService.java:266)
        at com.github.kfcfans.powerjob.server.service.instance.InstanceService.stopInstance(InstanceService.java:98)
        at com.github.kfcfans.powerjob.server.web.controller.InstanceController.stopInstance(InstanceController.java:63)
        at com.github.kfcfans.powerjob.server.web.controller.InstanceController$$FastClassBySpringCGLIB$$7858e390.invoke(<generated>)

**Comment by KFCFans** [comment]
postgresql 属于关系型数据库中的奇葩特例...JPA 没办法很好的兼容，用这个数据库需要自己稍微修改下 powerjob-server 代码，抱歉。
