### ISSUE TITLE
在处理器里写自己的业务代码

### ISSUE THREAD

**Issue by cjh19940522** [KFCFans/PowerJob#83]
我自己在mapreduceprocess  中 写的业务代码   执行成功后  会报这个空指针  控制不住

java.lang.NullPointerException: null
	at com.github.kfcfans.powerjob.worker.core.executor.ProcessorRunnable.innerRun(ProcessorRunnable.java:139)
	at com.github.kfcfans.powerjob.worker.core.executor.ProcessorRunnable.run(ProcessorRunnable.java:192)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-10-15 19:40:26] [oms-akka.task-tracker-dispatcher-19] [INFO] [com.github.kfcfans.powerjob.worker.core.tracker.task.TaskTracker:218] [TaskTracker-197073636752883904-197073636752883904] task(taskId=1111) process failed, TaskTracker will have a retry.
[2020-10-15 19:40:31] [oms-processor-pool-0] [ERROR] [com.github.kfcfans.powerjob.worker.core.executor.ProcessorRunnable:196] [ProcessorRunnable-197073636752883904] execute failed, please contact the author(@KFCFans) to fix the bug!
java.lang.NullPointerException: null
	at com.github.kfcfans.powerjob.worker.core.executor.ProcessorRunnable.innerRun(ProcessorRunnable.java:139)
	at com.github.kfcfans.powerjob.worker.core.executor.ProcessorRunnable.run(ProcessorRunnable.java:192)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KFCFans** [comment]
不正常使用导致，看一眼源码报错的地方就知道了。
返回框架要求返回的数据了吗？
看 demo 怎么写的了吗？
