### ISSUE TITLE
server启动报空指针异常

### ISSUE THREAD

**Issue by QuanbIn30** [KFCFans/PowerJob#87]
```java
java.lang.NullPointerException: null
	at com.github.kfcfans.powerjob.server.service.DispatchService.dispatch(DispatchService.java:81)
	at com.github.kfcfans.powerjob.server.service.DispatchService.redispatch(DispatchService.java:51)
	at com.github.kfcfans.powerjob.server.service.timing.InstanceStatusCheckService.lambda$null$1(InstanceStatusCheckService.java:122)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.kfcfans.powerjob.server.service.timing.InstanceStatusCheckService.lambda$checkInstance$3(InstanceStatusCheckService.java:119)
	at java.lang.Iterable.forEach(Iterable.java:75)
```

**Comment by KFCFans** [comment]
请提供 PowerJob 的版本号、OS版本 等信息。

**Comment by QuanbIn30** [comment]
您好，谢谢您的回复。


powerjob版本号：V3.3.1
os版本号：Mac os Catalina (version: 10.15.3&nbsp;)


后来没动这个空指针异常好像又没有了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KFCFans/PowerJob"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午3:24
收件人:&nbsp;"KFCFans/PowerJob"<PowerJob@noreply.github.com&gt;;
抄送:&nbsp;"全彬"<821996940@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KFCFans/PowerJob] server启动报空指针异常 (#87)





 
请提供 PowerJob 的版本号、OS版本 等信息。

**Comment by KFCFans** [comment]
maxInstanceNum 为 null 导致，应该使用了非法的 API。
下个版本会加上空保护。
